### ISSUE TITLE
Virtual creation on 11.5.4 causes unexpected json pair error

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-agent#1010]
#### OpenStack Release
liberty

#### Description
This was found in mitaka, but should be fixed in liberty and merged forward. We believe this is a bug with the way virtuals do a forward reference of a pool whether or not the pool exists. In mitaka the problem seems to lie [here](https://github.com/F5Networks/f5-openstack-agent/blob/mitaka/f5_openstack_agent/lbaasv2/drivers/bigip/service_adapter.py#L123), where we set the pool's value in the virtual's dict, even though some entries in the pool's dictionary may be empty (such as name). Here's a traceback of the error:

```
2017-10-05 15:05:53.021 23336 DEBUG root [req-5b01d494-39ad-4a43-b247-cdc812afb01e b61daacd97cb4411b82a8761b9ea07d6 91e7fbe8dcf44fe99778029f0828c605 - - -] post WITH uri: https://10.190.7.237:443/mgmt/tm/ltm/virtual/ AND suffix:  AND kwargs: {'json': {'partition': u'Project_91e7fbe8dcf44fe99778029f0828c605', 'name': u'Project_86ed0524-5fde-402c-bfee-6190d3d20087', 'destination': u'10.2.4.3%1:80', 'enabled': True, 'profiles': ['/Common/http', '/Common/oneconnect'], 'vlansEnabled': True, 'fallbackPersistence': '', 'sourceAddressTranslation': {'type': 'snat', 'pool': u'Project_91e7fbe8dcf44fe99778029f0828c605'}, 'connectionLimit': 0, 'persist': [], 'ipProtocol': 'tcp', 'vlans': ['tunnel-vxlan-65'], 'pool': {'partition': u'Project_91e7fbe8dcf44fe99778029f0828c605', 'name': ''}, 'description': u''}} wrapper /usr/lib/python2.7/site-packages/icontrol/session.py:257
2017-10-05 15:05:53.031 23336 DEBUG root [req-5b01d494-39ad-4a43-b247-cdc812afb01e b61daacd97cb4411b82a8761b9ea07d6 91e7fbe8dcf44fe99778029f0828c605 - - -] RESPONSE::STATUS: 400 Content-Type: application/json Content-Encoding: None
Text: u'{"code":400,"message":"Found unexpected json pair at property /ltm/virtual/~Project_91e7fbe8dcf44fe99778029f0828c605~Project_86ed0524-5fde-402c-bfee-6190d3d20087/pool. The json pair is \\"name\\":\\"\\".","errorStack":[]}' wrapper /usr/lib/python2.7/site-packages/icontrol/session.py:265
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service [req-5b01d494-39ad-4a43-b247-cdc812afb01e b61daacd97cb4411b82a8761b9ea07d6 91e7fbe8dcf44fe99778029f0828c605 - - -] Virtual server creation error: 400 Unexpected Error: Bad Request for uri: https://10.190.7.237:443/mgmt/tm/ltm/virtual/
Text: u'{"code":400,"message":"Found unexpected json pair at property /ltm/virtual/~Project_91e7fbe8dcf44fe99778029f0828c605~Project_86ed0524-5fde-402c-bfee-6190d3d20087/pool. The json pair is \\"name\\":\\"\\".","errorStack":[]}'
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service Traceback (most recent call last):
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/listener_service.py", line 66, in create_listener
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service     self.vs_helper.create(bigip, vip)
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/resource_helper.py", line 94, in create
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service     obj = resource.create(**model)
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service   File "/usr/lib/python2.7/site-packages/f5/bigip/resource.py", line 974, in create
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service     return self._create(**kwargs)
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service   File "/usr/lib/python2.7/site-packages/f5/bigip/resource.py", line 941, in _create
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service     response = session.post(_create_uri, json=kwargs, **requests_params)
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service   File "/usr/lib/python2.7/site-packages/icontrol/session.py", line 272, in wrapper
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service     raise iControlUnexpectedHTTPError(error_message, response=response)
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://10.190.7.237:443/mgmt/tm/ltm/virtual/
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service Text: u'{"code":400,"message":"Found unexpected json pair at property /ltm/virtual/~Project_91e7fbe8dcf44fe99778029f0828c605~Project_86ed0524-5fde-402c-bfee-6190d3d20087/pool. The json pair is \\"name\\":\\"\\".","errorStack":[]}'
2017-10-05 15:05:53.032 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.listener_service
2017-10-05 15:05:53.035 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-5b01d494-39ad-4a43-b247-cdc812afb01e b61daacd97cb4411b82a8761b9ea07d6 91e7fbe8dcf44fe99778029f0828c605 - - -] 400 Unexpected Error: Bad Request for uri: https://10.190.7.237:443/mgmt/tm/ltm/virtual/
Text: u'{"code":400,"message":"Found unexpected json pair at property /ltm/virtual/~Project_91e7fbe8dcf44fe99778029f0828c605~Project_86ed0524-5fde-402c-bfee-6190d3d20087/pool. The json pair is \\"name\\":\\"\\".","errorStack":[]}'
2017-10-05 15:05:53.035 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Traceback (most recent call last):
2017-10-05 15:05:53.035 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 1433, in _common_service_handler
2017-10-05 15:05:53.035 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     all_subnet_hints)
2017-10-05 15:05:53.035 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/lbaas_builder.py", line 61, in assure_service
2017-10-05 15:05:53.035 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     self._assure_listeners_created(service)
2017-10-05 15:05:53.035 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/lbaas_builder.py", line 169, in _assure_listeners_created
2017-10-05 15:05:53.035 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     raise f5_ex.VirtualServerCreationException(err.message)
2017-10-05 15:05:53.035 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver VirtualServerCreationException: 400 Unexpected Error: Bad Request for uri: https://10.190.7.237:443/mgmt/tm/ltm/virtual/
2017-10-05 15:05:53.035 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Text: u'{"code":400,"message":"Found unexpected json pair at property /ltm/virtual/~Project_91e7fbe8dcf44fe99778029f0828c605~Project_86ed0524-5fde-402c-bfee-6190d3d20087/pool. The json pair is \\"name\\":\\"\\".","errorStack":[]}'
2017-10-05 15:05:53.035 23336 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver
```

**Comment by dflanigan** [comment]
@pjbreaux has this been fixed ?

**Comment by pjbreaux** [comment]
@dflanigan: yes, this should close when we merge to master.
