### ISSUE TITLE
using common_network_ids

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-openstack-agent#332]
#### OpenStack Release

Mitka
#### Description

I'm trying to load the f5-openstack-agent using the common_network_ids parameter and I'm always getting an error.  Is this a supported option?  Looking at the source code it looks like it will always fail unless I'm not seeing the right code:

error from f5-openstack-agent.log

```
2016-09-28 10:33:28.511 6896 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-82118439-4ee0-46d3-8a0d-c5a5acc4d2de - - - - -] Could not communicate with all iControl devices: Common network external on 10.1.30.245 does not exist
2016-09-28 10:33:33.516 6896 CRITICAL neutron [req-82118439-4ee0-46d3-8a0d-c5a5acc4d2de - - - - -] MissingNetwork: Common network external on 10.1.30.245 does not exist
2016-09-28 10:33:33.516 6896 ERROR neutron Traceback (most recent call last):
2016-09-28 10:33:33.516 6896 ERROR neutron   File "/usr/bin/f5-oslbaasv2-agent", line 9, in <module>
2016-09-28 10:33:33.516 6896 ERROR neutron     load_entry_point('f5-openstack-agent==9.0.3', 'console_scripts', 'f5-oslbaasv2-agent')()
2016-09-28 10:33:33.516 6896 ERROR neutron   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/agent.py", line 69, in main
2016-09-28 10:33:33.516 6896 ERROR neutron     mgr = manager.LbaasAgentManager(cfg.CONF)
2016-09-28 10:33:33.516 6896 ERROR neutron   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py", line 232, in __init__
2016-09-28 10:33:33.516 6896 ERROR neutron     self._load_driver(conf)
2016-09-28 10:33:33.516 6896 ERROR neutron   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py", line 280, in _load_driver
2016-09-28 10:33:33.516 6896 ERROR neutron     self.conf)
2016-09-28 10:33:33.516 6896 ERROR neutron   File "/usr/lib/python2.7/site-packages/oslo_utils/importutils.py", line 44, in import_object
2016-09-28 10:33:33.516 6896 ERROR neutron     return import_class(import_str)(*args, **kwargs)
2016-09-28 10:33:33.516 6896 ERROR neutron   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 343, in __init__
2016-09-28 10:33:33.516 6896 ERROR neutron     self.connect_bigips()
2016-09-28 10:33:33.516 6896 ERROR neutron   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 351, in connect_bigips
2016-09-28 10:33:33.516 6896 ERROR neutron     self._init_bigips()
2016-09-28 10:33:33.516 6896 ERROR neutron   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 487, in _init_bigips
2016-09-28 10:33:33.516 6896 ERROR neutron     self._init_bigip(first_bigip, self.hostnames[0], None)
2016-09-28 10:33:33.516 6896 ERROR neutron   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 566, in _init_bigip
2016-09-28 10:33:33.516 6896 ERROR neutron     % (network, bigip.hostname))
2016-09-28 10:33:33.516 6896 ERROR neutron MissingNetwork: Common network external on 10.1.30.245 does not exist
2016-09-28 10:33:33.516 6896 ERROR neutron
```

BIG-IP

```
root@(localhost)(cfg-sync Standalone)(Active)(/Common)(tmos.net)# list /net vlan
net vlan data {
    if-index 64
    interfaces {
        1.1 {
            tagged
        }
    }
    tag 30
}
net vlan external {
    if-index 96
    interfaces {
        1.1 {
            tagged
        }
    }
    tag 10
}
```

lbaasv2/drivers/bigip/icontrol_driver.py

```
        if self.network_builder:
            for network in self.conf.common_network_ids.values():
                if not self.network_builder.vlan_exists(network,
                                                        folder='Common'):
                    raise f5ex.MissingNetwork(
                        'Common network %s on %s does not exist'
                        % (network, bigip.hostname))
```

lbaasv2/drivers/bigip/network_service.py

```
    def vlan_exists(self, network, folder='Common'):
        return False
```
#### Agent Version

f5-openstack-agent-9.0.3-1.noarch
#### Operating System

centos7
#### OpenStack Release

Mitika

**Comment by alonsocamaro** [comment]
I've just tested this in 9.1 and it is working for me. Is this bug really open?

**Comment by dflanigan** [comment]
Rich completed work on Nov 18.
