### ISSUE TITLE
tunnel_sync in the iControl driver can check for an undefined attribute

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-agent#368]
#### OpenStack Release

Liberty, Mitaka
#### Description

In the tunnel_sync method of icontrol_driver.iControlDriver in a loop of all connected BIG-IPs, check:

```
if bigip.local_ip:
    tunnel_ips.append(bigip.local_ip)
```

the local_ip attribute is not always defined in all configurations.
#### Deployment

Deploy the agent with VLANs only.

tunnel_sync will generate:

```
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task [-] Error during LbaasAgentManager.periodic_resync
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task Traceback (most recent call last):
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task   File "/usr/lib/python2.7/dist-packages/oslo_service/periodic_task.py", line 220, in run_periodic_tasks
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task     task(self, context)
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task   File "/usr/lib/python2.7/dist-packages/f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py", line 423, in periodic_resync
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task     if self.tunnel_sync():
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task   File "/usr/lib/python2.7/dist-packages/f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py", line 431, in tunnel_sync
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task     return self.lbdriver.tunnel_sync()
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task   File "/usr/lib/python2.7/dist-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 951, in tunnel_sync
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task     if bigip.local_ip:
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task   File "/usr/lib/python2.7/dist-packages/f5/bigip/mixins.py", line 100, in __getattr__
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task     raise AttributeError(error_message)
2016-10-07 12:30:53.965 7284 ERROR oslo_service.periodic_task AttributeError: '<class 'f5.bigip.ManagementRoot'>' object has no attribute 'local_ip'
```

**Comment by mattgreene** [comment]
Confirmed that this change made it into master, but the issue did not close automatically.
