### ISSUE TITLE
v9.1.0: python-f5-sdk_1.5.0-1_1404_all.deb wrongly depends on python-f5-icontrol-rest (= 1.0.9-1)

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-agent#390]
#### OpenStack Release
Mitaka

#### Description

Hi

When installing the phython-f5-sdk using the files indicated in the release notes of v9.1.0 I find the following problem.

```
root@node-5:~# sudo dpkg -i python-f5-sdk_1.5.0-1_1404_all.deb 
(Reading database ... 111336 files and directories currently installed.)
Preparing to unpack python-f5-sdk_1.5.0-1_1404_all.deb ...
Unpacking python-f5-sdk (1.5.0-1) over (1.5.0-1) ...
dpkg: dependency problems prevent configuration of python-f5-sdk:
 python-f5-sdk depends on python-f5-icontrol-rest (= 1.0.9-1); however:
  Version of python-f5-icontrol-rest on system is 1.1.0-1.

dpkg: error processing package python-f5-sdk (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 python-f5-sdk
```

Seems that the version of the dependencies have not been updated.

A new .deb file solving this would be greatly appreciated 

Thanks

        Ulises

#### Agent Version
9.0.1

#### Operating System
Mirantis 9

**Comment by alonsocamaro** [comment]
When I start the lbaas plugin I also find similar dependencies:

```
su - neutron -c /usr/bin/f5-oslbaasv2-agent -- --config-file /etc/neutron/services/f5/f5-openstack-agent.ini --config-file /etc/neutron/neutron.conf --log-file=/var/log/neutron/f5-oslbaasv2-agent.log
Traceback (most recent call last):
  File "/usr/bin/f5-oslbaasv2-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 642, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 828, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'f5-icontrol-rest==1.0.9' distribution was not found and is required by f5-sdk
```
Which f5-icontrol-rest package is expected the 9.1 release should be running?

**Comment by richbrowne** [comment]
Hi,

  The version that should be running is 1.0.9 of icontrol rest.  You need
to uninstall 1.10.0 of the icontrol-rest and reinstall based on these
instructions:


http://f5-openstack-agent.readthedocs.io/en/mitaka/index.html#home

Please refresh your screen if this still says the version is 1.10.0.


Rich

**Comment by alonsocamaro** [comment]
Many thanks Richard

It looks fine now

**Comment by richbrowne** [comment]
Fixed documentation
