### ISSUE TITLE
LBaaS object not created in expected routing domain

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-agent#402]
#### OpenStack Release
Mitaka

#### Description
When creating the following objects

```
neutron lbaas-loadbalancer-create --name test190 --vip-address 10.0.2.190 ext
neutron lbaas-loadbalancer-show test190
neutron lbaas-listener-create --loadbalancer test190 --protocol HTTP --protocol-port 80 --name test190

```
And the configuration is in use (full configuration at the bottom)

```
f5_global_routed_mode = False
use_namespaces = True
max_namespaces_per_tenant = 1
f5_route_domain_strictness = True
```
I would expect that the Project's partition would have assigned as default routing domain the routing domain created for the project. But it is not the case:

```
root@(bigip2)(cfg-sync Changes Pending)(Standby)(/Project_8e9b22cab67040689dcf86f74275a911)(tmos)# list auth partition Project_8e9b22cab67040689dcf86f74275a911 all-properties 
auth partition Project_8e9b22cab67040689dcf86f74275a911 {
    default-route-domain 0
    description none
}

```

For completness the VIP is not created in using the routing domain created for the partition:

```
ltm virtual test190 {
    destination 10.0.2.190:http
    ip-protocol tcp
    mask 255.255.255.255
    partition Project_8e9b22cab67040689dcf86f74275a911
    profiles {
        /Common/tcp { }
    }
    source 0.0.0.0/0
    source-address-translation {
        pool /Common/Project_8e9b22cab67040689dcf86f74275a911
        type snat
    }
    translate-address enabled
    translate-port enabled
    vlans {
        /Common/tunnel-vxlan-69
    }
    vlans-enabled
    vs-index 2
}

net route-domain Project_8e9b22cab67040689dcf86f74275a911 {
    id 1
    partition Project_8e9b22cab67040689dcf86f74275a911
}

```

#### Agent Version
9.1

#### Operating System
Mirantis 9

#### Deployment

root@node-5:/etc/neutron/services/f5# egrep -v ^# /etc/neutron/services/f5/f5-openstack-agent.ini 
[DEFAULT]
debug = True
periodic_interval = 10
f5_ha_type = scalen
f5_external_physical_mappings = default:1.1:True
f5_vtep_folder = 'Common'
f5_vtep_selfip_name = 'selfip.datanet'
advertised_tunnel_types = vxlan
f5_populate_static_arp = False
 
l2_population = false
f5_global_routed_mode = False
use_namespaces = True
max_namespaces_per_tenant = 1
f5_route_domain_strictness = True
f5_snat_mode = True
f5_snat_addresses_per_subnet = 1
f5_common_external_networks = False
f5_bigip_lbaas_device_driver = f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver.iControlDriver
icontrol_hostname = 10.128.5.237,10.128.5.238
icontrol_username = admin
icontrol_password = admin
auth_version = v3
os_auth_url = http://localhost:5000/v3
os_username = admin
os_password = changeme
os_user_domain_name = default
os_project_name = admin
os_project_domain_name = default
f5_parent_ssl_profile = clientssl

**Comment by alonsocamaro** [comment]
Changing the Partition's default-routing domain fixes the issue. I was able to create objects and delete them. Seems that only the Partition's creation needs to be fixed.

**Comment by alonsocamaro** [comment]
Actually... it turns out not to be true my previous post:

```
Text: u'{"code":400,"message":"0107097c:3: The specified route domain (1) is the default route domain for one or more partitions (Project_8e9b22cab67040689dcf86f74275a911) and cannot be deleted.","errorStack":[],"apiError":3}'
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants Traceback (most recent call last):
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants   File "/usr/lib/python2.7/dist-packages/f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py", line 141, in _remove_tenant_replication_mode
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants     self.system_helper.delete_folder(bigip, partition)
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants   File "/usr/lib/python2.7/dist-packages/f5_openstack_agent/lbaasv2/drivers/bigip/system_helper.py", line 41, in delete_folder
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants     obj.delete()
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants   File "/usr/lib/python2.7/dist-packages/f5/bigip/resource.py", line 947, in delete
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants     self._delete(**kwargs)
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants   File "/usr/lib/python2.7/dist-packages/f5/bigip/resource.py", line 929, in _delete
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants     response = session.delete(delete_uri, **requests_params)
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants   File "/usr/lib/python2.7/dist-packages/icontrol/session.py", line 230, in wrapper
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants     raise iControlUnexpectedHTTPError(error_message, response=response)
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://10.128.5.237:443/mgmt/tm/sys/folder/~Project_8e9b22cab67040689dcf86f74275a911/
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants Text: u'{"code":400,"message":"0107082a:3: All objects must be removed from a partition (Project_8e9b22cab67040689dcf86f74275a911) before the partition may be removed, type ID (6085)","errorStack":[],"apiError":3}'
2016-10-31 15:35:05.951 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.tenants 
2016-10-31 15:35:05.992 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-582e041b-918f-4f16-a755-aefa1465d9c8 13eeaa5d6b8b4916b695e894968c9a93 8e9b22cab67040689dcf86f74275a911 - - -] Failed to destroy folder Project_8e9b22cab67040689dcf86f74275a911 manual cleanup might be required.
2016-10-31 15:35:05.992 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Traceback (most recent call last):
2016-10-31 15:35:05.992 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/dist-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 1145, in _common_service_handler
2016-10-31 15:35:05.992 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     all_subnet_hints)
2016-10-31 15:35:05.992 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/dist-packages/f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py", line 107, in assure_tenant_cleanup
2016-10-31 15:35:05.992 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     self._assure_bigip_tenant_cleanup(bigip, service, subnet_hints)
2016-10-31 15:35:05.992 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/dist-packages/f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py", line 114, in _assure_bigip_tenant_cleanup
2016-10-31 15:35:05.992 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     self._remove_tenant_replication_mode(bigip, tenant_id)
2016-10-31 15:35:05.992 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/dist-packages/f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py", line 149, in _remove_tenant_replication_mode
2016-10-31 15:35:05.992 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     "required." % partition)
2016-10-31 15:35:05.992 6467 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver SystemDeleteException: Failed to destroy folder Project_8e9b22cab67040689dcf86f74275a911 manual cleanup might be required.

```

So further actions seem that are necessary.

If this is not a bug please describe how is this feature expected to be used.

Many thanks
