### ISSUE TITLE
L7 policy fails to delete when one policy is remaining

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-agent#435]
#### OpenStack Release
applicable to feature.l7switching

#### Description
An l7policy with a provisioning status of PENDING_DELETE fails to delete due to the fact that we are not filtering policies with the above status properly. This can be done in l7policy_service module for update and create. We need to check that the build_policy method actually didn't filter out all policies before doing a translate. Here is the error that was shown in the agent log. Might be helpful to allow that exception message to bubble up to the log.

```
Text: u'{"code":404,"message":"Object not found - wrapper_policy","errorStack":[],"apiError":1}' wrapper /usr/lib/python2.7/site-packages/icontrol/session.py:234
2016-11-22 14:13:22.228 16582 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-0998137a-a513-4b92-b26b-4986406fc60f bc987204a1614be2aa4c0b32a3c66645 9efe
e0172512443ca2d39dfca4b54a24 - - -] 404 Unexpected Error: Not Found for uri: https://10.190.7.221:443/mgmt/tm/ltm/virtual/~Project_9efee0172512443ca2d39dfca4b54a24~Project_
d5ffc1c0-f020-4b18-a6bf-17d10d5be5ff/policies/
Text: u'{"code":404,"message":"Object not found - wrapper_policy","errorStack":[],"apiError":1}'
2016-11-22 14:13:22.228 16582 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Traceback (most recent call last):
2016-11-22 14:13:22.228 16582 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/big
ip/icontrol_driver.py", line 1285, in _common_service_handler
2016-11-22 14:13:22.228 16582 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     all_subnet_hints)
2016-11-22 14:13:22.228 16582 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/lbaas_builder.py", line 61, in assure_service
2016-11-22 14:13:22.228 16582 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     self._assure_l7policies_created(service)
2016-11-22 14:13:22.228 16582 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/lbaas_builder.py", line 415, in _assure_l7policies_created
2016-11-22 14:13:22.228 16582 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     raise f5_ex.L7PolicyCreationException(err.message)
2016-11-22 14:13:22.228 16582 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver L7PolicyCreationException: 404 Unexpected Error: Not Found for uri: https://10.190.7.221:443/mgmt/tm/ltm/virtual/~Project_9efee0172512443ca2d39dfca4b54a24~Project_d5ffc1c0-f020-4b18-a6bf-17d10d5be5ff/policies/
2016-11-22 14:13:22.228 16582 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Text: u'{"code":404,"message":"Object not found - wrapper_policy","errorStack":[],"apiError":1}'
2016-11-22 14:13:22.228 16582 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver
```

**Comment by pjbreaux** [comment]
Fixed by PR #429
