### ISSUE TITLE
Nightly regression failure for `test_nosegid_to_segid`

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-agent#463]
@dflanigan @mattgreene @swormke

Title: The test_nosegid_to_segid "neutronless" test has failed in the nightly regression every night from 2016-12-02 -- 2016-12-05.
This is tracked internally here:

http://trtl.pdbld.f5net.com/gumballs/projects/f5-openstack-agent/

and here:

https://jira.pdsea.f5net.com/browse/OPENSTACK-682

I'll note progress in this comment thread.

**Comment by zancas** [comment]
During reproduction on the liberty branch I see that the issue is not triggered during the run of the test, but an ERROR during teardown.

**Comment by zancas** [comment]
I noticed that the version pinning bugfix for neutron has not landed yet due to a stale branch divergence (fixed with rebase).

I rebased and pushed that fix.

Since I expect that to land, and I don't want to have noise from the pinning issue #450 while debugging this one, I'm basing this fix on top of the fixed branch.

**Comment by zancas** [comment]
Interesting traceback:

```
test_disconnected_service_creation.py::test_nosegid_to_segid PASSEDTraceback (most recent call last):
  File "/home/ubuntu/systest/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 457, in fire_timers
    timer()
  File "/home/ubuntu/systest/local/lib/python2.7/site-packages/eventlet/hubs/timer.py", line 58, in __call__
    cb(*args, **kw)
  File "/home/ubuntu/systest/local/lib/python2.7/site-packages/eventlet/greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "/home/ubuntu/f5-openstack-agent/f5_openstack_agent/lbaasv2/drivers/bigip/disconnected_service.py", line 154, in polling_thread
    self.scan()
  File "/home/ubuntu/f5-openstack-agent/f5_openstack_agent/lbaasv2/drivers/bigip/disconnected_service.py", line 77, in scan
    loadbalancer_ids = d.plugin_rpc.get_all_loadbalancers()
  File "/home/ubuntu/systest/local/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/home/ubuntu/systest/local/lib/python2.7/site-packages/mock/mock.py", line 1121, in _mock_call
    result = next(effect)
  File "/home/ubuntu/systest/local/lib/python2.7/site-packages/mock/mock.py", line 109, in next
    return _next(obj)
StopIteration
```

**Comment by zancas** [comment]
StopIteration is the signal to a the consumer that the end of the Iterator has been reached...  perhaps we have a mock that doesn't properly handle this case?

**Comment by zancas** [comment]
`plugin_rpc` _is_ a mock of an iterable in this test-case.   Perhaps I just need to have `.get_all_loadbalancers()` return an Iterator...

**Comment by zancas** [comment]
When I manually run the `{TUNNEL_FDB}.update(records=[])` followed by `{TUNNEL}.delete()` the object is correctly deleted.

If I run the test repeatedly the cleanup ERROR only occurs on the first run, (since subsequent run will not attempt to delete a resource that already existed).

**Comment by zancas** [comment]
Since all the assertions within the test pass, I believe this is a test bug.

**Comment by zancas** [comment]
I suspect the `StopIteration` error may be caused by the multi-threaded code trying to access the rpc_plugin after it's already exhausted.   That is, I suspect one of the threads exhausts the Iterator, then another comes along calls `next()` on the same object.

This could happen if more than one thread has a:

`for x in Iterator_from_rpc_plugin.get_all_loadbalancers()`

operation.    Where the 'Iterator_from_rpc_plugin.get_all_loadbalancers()' object is shared.

**Comment by zancas** [comment]
Observation:   There's a time sleep in the middle of the test.
Observation:   The agent periodically "scans" which means it obtains the "truth" about the state of the device from "neutron" and sets it.
Hypothesis:     The time sleep in the test and the periodic scan are of approximately the same interval, this causes the agent to reset the device with e.g. DB entries, during the teardown.   This causes teardown to ERROR out.

**Comment by zancas** [comment]
`icontroldriver.conf.f5_network_segment_gross_timeout == 5`

It seems like this variable is both how long the mid-test sleep is, and the amount of time in between launches of the polling threads.

**Comment by zancas** [comment]
I now believe this is a test issue.
There are multiple threads of execution (an architectural decision I had no input in).
In the test the `rpc_plugin` is polled by `DisconnectedServicePolling` instances.

In the test the *mock* rpc_plugin responds with assertions about the state of the loadbalancer.
The test teardown error probably occurs when, after the teardown code purges the fdb records, a separate thread recreates them (because the mock rpc_plugin has specified that it should).

The fix is to make the teardown code more robust to stale (spontaneous) fdb entries.

The fix was accidentally merged along with the 'neutron pinning' fix yesterday.
