### ISSUE TITLE
neutronless tests generate non-deterministic tracebacks.

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-agent#466]
Note that the below did _not_ cause a test failure!   Also note that this traceback was generate by:

"`File "/home/ubuntu/f5-openstack-agent/f5_openstack_agent/lbaasv2/drivers/bigip/disconnected_service.py", line 154, in polling_thread
    self.scan()`"

```
(systest) ubuntu@disconnected-v8:~/f5-openstack-agent/test/functional/neutronless/disconnected_service$ while [ $? == 0 ]; do py.test -vlsx --symbols ~/testenv_symbols/testenv_symbols.json -- .; done
<class 'f5.bigip.BigIP'>
======================================================== test session starts ========================================================
platform linux2 -- Python 2.7.12, pytest-3.0.3, py-1.4.31, pluggy-0.4.0 -- /home/ubuntu/systest/bin/python
cachedir: ../../../../../.cache
pytest-autolog: outputdir is /home/ubuntu/f5-openstack-agent/test/functional/neutronless/disconnected_service/test_results/20161205-230812
pytest-autolog: trace is disabled
rootdir: /home/ubuntu, inifile:
plugins: symbols-0.1.0a3, meta-0.1.0a3, cov-2.3.1, autolog-0.1.0a3, f5-openstack-test-0.2.0
collected 11 items
pytest-meta: discarded 0 items

test_disconnected_service_creation.py::test_featureoff_withsegid_lb PASSED
test_disconnected_service_creation.py::test_withsegid_lb PASSED
test_disconnected_service_creation.py::test_featureoff_withsegid_listener PASSED
test_disconnected_service_creation.py::test_featureoff_nosegid_lb PASSED
test_disconnected_service_creation.py::test_featureoff_nosegid_listener PASSED
test_disconnected_service_creation.py::test_withsegid_listener PASSED
test_disconnected_service_creation.py::test_nosegid_lb PASSED
test_disconnected_service_creation.py::test_nosegid_listener PASSED
test_disconnected_service_creation.py::test_nosegid_listener_timeout PASSED
test_disconnected_service_creation.py::test_nosegid_to_segid PASSED
test_disconnected_service_creation.py::test_featureoff_grm_lb Traceback (most recent call last):
  File "/home/ubuntu/systest/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 457, in fire_timers
    timer()
  File "/home/ubuntu/systest/local/lib/python2.7/site-packages/eventlet/hubs/timer.py", line 58, in __call__
    cb(*args, **kw)
  File "/home/ubuntu/systest/local/lib/python2.7/site-packages/eventlet/greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "/home/ubuntu/f5-openstack-agent/f5_openstack_agent/lbaasv2/drivers/bigip/disconnected_service.py", line 154, in polling_thread
    self.scan()
  File "/home/ubuntu/f5-openstack-agent/f5_openstack_agent/lbaasv2/drivers/bigip/disconnected_service.py", line 144, in scan
    bigips, virtual)
  File "/home/ubuntu/f5-openstack-agent/f5_openstack_agent/lbaasv2/drivers/bigip/disconnected_service.py", line 45, in get_service_virtual_address
    name=virtual['name'], partition=virtual['partition'])
  File "/home/ubuntu/systest/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 915, in load
    return self._load(**kwargs)
  File "/home/ubuntu/systest/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 894, in _load
    response = refresh_session.get(base_uri, **kwargs)
  File "/home/ubuntu/systest/local/lib/python2.7/site-packages/icontrol/session.py", line 230, in wrapper
    raise iControlUnexpectedHTTPError(error_message, response=response)
iControlUnexpectedHTTPError: 404 Unexpected Error: Not Found for uri: https://10.2.2.61:443/mgmt/tm/ltm/virtual/~TEST_128a63ef33bc4cf891d684fad58e7f2d~TEST_105a227a-cdbf-4ce3-844c-9ebedec849e9
Text: u'{"code":404,"message":"01020036:3: The requested Virtual Server (/TEST_128a63ef33bc4cf891d684fad58e7f2d/TEST_105a227a-cdbf-4ce3-844c-9ebedec849e9) was not found.","errorStack":[],"apiError":3}'
PASSED

==================================================== 11 passed in 195.87 seconds ====================================================
```

I'm testing on liberty.

**Comment by zancas** [comment]
It seems like we might need to add some more defensive `try` `except` code around the scanning routine.

**Comment by zancas** [comment]
I think this is a test artifact where our static service objects pass invalid data to the scanner that is running periodically during the tests.

**Comment by zancas** [comment]
This is a test artifact caused by "stray" greenthreads polling the stale rpc_plugin.
