### ISSUE TITLE
Disconnected test test_nosegid_to_segid errors consistently during teardown

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-agent#550]
Need to understand this issue.  Run the following command in against the default testenv bigip:

# Create testenv
testenv  create --name bigip-12.1 --config bigip

# Run the functest
tox -e functest -- --symbols ./testenv_symbols/testenv_symbols.json  test/functional/neutronless/disconnected_service/test_disconnected_service_creation.py

nosegid_to_segid fails:

neutronless/disconnected_service/test_disconnected_service_creation.py::test_nosegid_to_segid PASSEDTraceback (most recent call last):
  File "/Users/rbrowne/Projects/richbrowne/f5-openstack-agent/.tox/functest/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 457, in fire_timers
    timer()
  File "/Users/rbrowne/Projects/richbrowne/f5-openstack-agent/.tox/functest/lib/python2.7/site-packages/eventlet/hubs/timer.py", line 58, in __call__
    cb(*args, **kw)
  File "/Users/rbrowne/Projects/richbrowne/f5-openstack-agent/.tox/functest/lib/python2.7/site-packages/eventlet/greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "/Users/rbrowne/Projects/richbrowne/f5-openstack-agent/f5_openstack_agent/lbaasv2/drivers/bigip/disconnected_service.py", line 154, in polling_thread
    self.scan()
  File "/Users/rbrowne/Projects/richbrowne/f5-openstack-agent/f5_openstack_agent/lbaasv2/drivers/bigip/disconnected_service.py", line 77, in scan
    loadbalancer_ids = d.plugin_rpc.get_all_loadbalancers()
  File "/Users/rbrowne/Projects/richbrowne/f5-openstack-agent/.tox/functest/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/rbrowne/Projects/richbrowne/f5-openstack-agent/.tox/functest/lib/python2.7/site-packages/mock/mock.py", line 1121, in _mock_call
    result = next(effect)
  File "/Users/rbrowne/Projects/richbrowne/f5-openstack-agent/.tox/functest/lib/python2.7/site-packages/mock/mock.py", line 109, in next
    return _next(obj)
StopIteration

**Comment by mattgreene** [comment]
This test is moving to the driver repo since HPB now requires agent_manager-level threading tests instead of icontroldriver greenthread.

**Comment by richbrowne** [comment]
Fixed.
