### ISSUE TITLE
L7 policy and loadbalancer partition cannot be deleted by the agent

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-agent#601]
* Title: Basic CRUD test of creation up to an L7 Rule results in the loadbalancer not being deletable in an unacceptable form of the L7 Policy
* Attachments: For bugs, attach the agent log and configuration files
  * [f5-openstack-agent.log.gz](https://github.com/F5Networks/f5-openstack-agent/files/814723/f5-openstack-agent.log.gz)
  * [rpc_log.log.gz](https://github.com/F5Networks/f5-openstack-agent/files/814724/rpc_log.log.gz)
    * A basic log containing the RPC calls back and forth
  * [crud_driver.txt.gz](https://github.com/F5Networks/f5-openstack-agent/files/814779/crud_driver.txt.gz)
    * The CRUD test used to cause this bug

#### Agent Version
9.2.0

#### Operating System
CentOS 7

#### OpenStack Release
Mitaka

#### Description
So following the commands:
`neutron subnet-create --gateway 10.22.22.1 --allocation_pool start=10.22.22.2,end=10.22.22.40 --enable-dhcp --name tst_sub testlab-server-network 10.22.22.0/22 2>&1`
`neutron lbaas-loadbalancer-create --name tst_b tst_sub  2>&1`
`neutron lbaas-listener-create --name tst_listener --protocol HTTP --protocol-port 80 --loadbalancer tst_b 2>&1`
`neutron lbaas-pool-create --name tst_pool --protocol HTTP --lb-algorithm ROUND_ROBIN --loadbalancer tst_b 2>&1`
`neutron lbaas-member-create --name member0 --protocol HTTP --protocol-port 80 --address 10.22.22.6 --subnet tst_sub tst_pool 2>&1`
`neutron lbaas-healthmonitor-create --max-width 5 --name mon0 --http-method GET --url-path /funstuff --max-retries 4 --timeout 2 --type HTTP --pool tst_pool --delay 2 2>&1`
`neutron lbaas-l7policy-create --max-width 3 --action REDIRECT_TO_URL --description foodogzoo --redirect-url http://10.22.22.6 --listener tst_listener --name tst_policy 2>&1`
`["neutron lbaas-l7rule-create tst_policy --type PATH --compare-type CONTAINS --key 'foo' --value 'foo' 2>&1"]`
`neutron lbaas-l7rule-list tst_policy | perl -ne \'/([0-9a-f]+-[0-9a-f]+\\S+)/;$id = $1;print "$id\n" if($id)\' 2>&1`
`neutron lbaas-l7rule-delete  tst_policy 2>&1`
`neutron lbaas-l7policy-delete tst_policy 2>&1`
`neutron lbaas-healthmonitor-delete mon0 2>&1`
`neutron lbaas-member-delete member0 tst_pool 2>&1`
`neutron lbaas-pool-delete tst_pool 2>&1`
`neutron lbaas-listener-delete tst_listener 2>&1`
`neutron lbaas-loadbalancer-delete tst_b 2>&1`
`neutron subnet-delete tst_sub 2>&1`
With a sleep between each of about 15 seconds results in a stream of errors.  Please note that the `2> &1` bit in Bash is simply piping the `STDERR` into the `STDOUT`; thus, I don't feel like this should be an issue.  I can recreate without this, though if so desired.

Another note is that the `perl` call is simply tailoring the result to just the `id` of the `l7rule` object.  I believe that this is irrelevant as the parsing is simply taking the print statement and performing parsing upon it.  This is generated and driven by a python script (attached). 

Upon the attempted deletion of the L7 Profile/Rule I get a traceback stating that it can't.  However, it also already stated that it can't create them, so we are causing some kind of residual state on the BIG IP.  When the loadbalancer is then deleted, the BIG IP REST comes back and states that it can't be performed.  This likely results in all kinds of unknown behavior that may be disruptive to traffic (unknown variable).

#### Deployment
This was produced in the testlab today using the testlab user's keystone profile.

**Comment by ssorenso** [comment]
This may be related to #577; however, I felt that it was slightly different as I would expect from a provisioning status issue to be resolved upon the deletion of all rules on the policy, and the policy to then be deleted.  This is a locked status that keeps the objects from being deleted at a `neutron` level.

**Comment by ssorenso** [comment]
So I have not been able to reproduce this on the BIG-IP® v12.1.1.  This was originally produced on v11.1.1 to my recollection, though it's been a few months.  To verify that it hits this version of the BIG-IP, I'm in the middle of setting up a stack.  I hope to recreate or isolate away this as a possibility for this.

**Comment by ssorenso** [comment]
Found a semi-relevant Traceback while attempting to reproduce this:
```
Text: u'{"kind":"tm:ltm:virtual:policies:policiescollectionstate","selfLink":"https://localhos
t/mgmt/tm/ltm/virtual/~Project_54ff910be48b4f81b359273845b9e225~Project_154f9c81-758a-4f73-ad4
8-40dc98adffe1/policies?ver=12.1.1","items":[{"kind":"tm:ltm:virtual:policies:policiesstate","
name":"wrapper_policy","partition":"Project_54ff910be48b4f81b359273845b9e225","fullPath":"/Pro
ject_54ff910be48b4f81b359273845b9e225/wrapper_policy","generation":105,"selfLink":"https://loc
alhost/mgmt/tm/ltm/virtual/~Project_54ff910be48b4f81b359273845b9e225~Project_154f9c81-758a-4f7
3-ad48-40dc98adffe1/policies/~Project_54ff910be48b4f81b359273845b9e225~wrapper_policy?ver=12.1
.1"}]}' wrapper /usr/lib/python2.7/site-packages/icontrol/session.py:265
2017-05-24 14:40:33.902 22369 DEBUG f5_openstack_agent.lbaasv2.drivers.bigip.vs_builder [req-8
67a4ceb-d66c-48f7-a47a-049c20d3724f b73d8ed467334c24a8f6600858a7b028 54ff910be48b4f81b35927384
5b9e225 - - -] Added L7 policy wrapper_policy for virtual sever Project_154f9c81-758a-4f73-ad4
8-40dc98adffe1 add_policy /usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/
bigip/vs_builder.py:83
2017-05-24 14:40:33.903 22369 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [
req-867a4ceb-d66c-48f7-a47a-049c20d3724f b73d8ed467334c24a8f6600858a7b028 54ff910be48b4f81b359
273845b9e225 - - -] 'iControlDriver' object has no attribute 'is_esd'
2017-05-24 14:40:33.903 22369 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Traceback (most recent call last):
2017-05-24 14:40:33.903 22369 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 1250, in _common_service_handler
2017-05-24 14:40:33.903 22369 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     all_subnet_hints)
2017-05-24 14:40:33.903 22369 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/lbaas_builder.py", line 65, in assure_service
2017-05-24 14:40:33.903 22369 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     self._assure_l7rules_created(service)
2017-05-24 14:40:33.903 22369 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/lbaas_builder.py", line 518, in _assure_l7rules_created
2017-05-24 14:40:33.903 22369 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     raise f5_ex.L7PolicyCreationException(err.message)
2017-05-24 14:40:33.903 22369 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver L7PolicyCreationException: 'iControlDriver' object has no attribute 'is_esd'
2017-05-24 14:40:33.903 22369 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver
2017-05-24 14:40:33.905 22369 DEBUG f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-867a4ceb-d66c-48f7-a47a-049c20d3724f b73d8ed467334c24a8f6600858a7b028 54ff910be48b4f81b359273845b9e225 - - -] _update_service_status update_service_status /usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py:1295
2017-05-24 14:40:33.906 22369 DEBUG f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-867a4ceb-d66c-48f7-a47a-049c20d3724f b73d8ed467334c24a8f6600858a7b028 54ff910be48b4f81b359273845b9e225 - - -] f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver.iControlDriver method _update_pool_status called with arguments ([{u'lb_algorithm': u'ROUND_ROBIN', u'listener_id': None, u'protocol': u'HTTP', u'description': u'', u'provisioning_status': u'ACTIVE', u'tenant_id': u'54ff910be48b4f81b359273845b9e225', u'l7_policies': [], u'loadbalancer_id': u'e2c04988-ce9d-42c1-9863-070d9fbcd8af', u'healthmonitor_id': u'61b23e3e-1705-48a3-98fc-3df7f0f15716', u'listeners': [], u'members': [{u'id': u'0f74e3ac-188f-47c5-8eb6-49892a34b6b7'}], u'admin_state_up': True, u'sessionpersistence': None, u'id': u'310cea29-c6ad-4af6-9658-7a11dcf43c26', u'operating_status': u'ONLINE'
```

**Comment by ssorenso** [comment]
as a test, I've locally changed the code to reflect:
```python
    510                     if name and hasattr(self.driver, 'is_esd') and \
    511                             self.driver.is_esd(name):
    512                         LOG.error("L7 policy {0} is an ESD. Cannot add "
    513                                   "an L7 rule to and ESD.".format(name))
    514                         continue
```
in `/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/lbaas_builder.py`.  not really seeing this as a permanent fix, but it is likely something that will get me a little further on that trail of getting the rule added.

The odd thing is that the message implies that it cannot add . the policy's rule; however, both the policy and the rule are now present on the BIG-IP... the issue now is that they cannot be deleted.

**Comment by ssorenso** [comment]
Analysis:
The `iControlDriver` no longer has the method `is_esd`.  This method was moved into the `LBaaSBuilder` class.
