### ISSUE TITLE
Misconfigured LOG var results in AttributeError: 'function' object has no attribute 'error'

### ISSUE THREAD

**Issue by busterswt** [F5Networks/f5-openstack-agent#685]
#### OpenStack Release
Newton

#### Agent Version
Master

#### Operating System
Ubuntu 16.04

#### OpenStack Release
Newton

#### Description
While executing certain operations, a traceback can be observed with the following error:

AttributeError: 'function' object has no attribute 'error'

This was found to

2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Traceback (most recent call last):
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 1214, in _common_service_handler
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     service, traffic_group)
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py", line 199, in prep_service_networking
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     self._assure_subnet_snats(assure_bigips, service, subnetinfo)
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py", line 564, in _assure_subnet_snats
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     subnetinfo, tenant_id, snats_per_subnet)
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/snats.py", line 88, in get_snat_addrs
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     fixed_address_count=1)
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/oslo_log/helpers.py", line 48, in wrapper
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     return method(*args, **kwargs)
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/plugin_rpc.py", line 365, in create_port_on_subnet
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     except messaging.MessageDeliveryFailure:
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver AttributeError: 'function' object has no attribute 'error'
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver
2017-05-03 20:08:19.600 19220 DEBUG f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-6809df5e-c8fd-4bab-980d-98c414d7ae2c 3c16178c83cd4a378b68c4bf50f7807a 62941e875f374220a5f712a01ff271fe - - -]     _prep_service_networking took 17.02674 secs _common_service_handler /openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py:1234
2017-05-03 20:08:19.601 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-6809df5e-c8fd-4bab-980d-98c414d7ae2c 3c16178c83cd4a378b68c4bf50f7807a 62941e875f374220a5f712a01ff271fe - - -] 'function' object has no attribute 'error'
2017-05-03 20:08:19.601 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Traceback (most recent call last):
2017-05-03 20:08:19.601 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 1230, in _common_service_handler
2017-05-03 20:08:19.601 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     raise error
2017-05-03 20:08:19.601 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver AttributeError: 'function' object has no attribute 'error'
2017-05-03 20:08:19.601 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver
2017-05-03 20:08:19.601 19220 DEBUG f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-6809df5e-c8fd-4bab-980d-98c414d7ae2c 3c16178c83cd4a378b68c4bf50f7807a 62941e875f374220a5f712a01ff271fe - - -] _update_service_status update_service_status /openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py:1296
2017-05-03 20:08:19.601 19220 DEBUG f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-6809df5e-c8fd-4bab-980d-98c414d7ae2c 3c16178c83cd4a378b68c4bf50f7807a 62941e875f374220a5f712a01ff271fe - - -] f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver.iControlDriver method _update_pool_status called with arguments ([],) {} wrapper /openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/oslo_log/helpers.py:47

#### Deployment
OpenStack-Ansible v14 (Newton) w/ 3 infra nodes. HA vCMP on i7800s

**Comment by pjbreaux** [comment]
@busterswt: what are the operations you were performing when seeing this error? How frequently does it happen?
