### ISSUE TITLE
Traceback when deleting pool member that doesn't have corresponding Neutron port

### ISSUE THREAD

**Issue by busterswt** [F5Networks/f5-openstack-agent#691]
#### OpenStack Release
Newton

#### Agent Version
Master

#### Operating System
Ubuntu 16.04

#### Description
When deleting pool members with the Neutron client (neutron lbaas-member-delete), the load balancer will go into an ERROR state if the pool member does not have a corresponding Neutron port. The traceback can be seen here:

2017-05-05 17:52:21.299 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-6eb29ee0-c7a0-409f-839b-f2314b803014 3c16178c83cd4a378b68c4bf50f7807a 62941e875f374220a5f712a01ff271fe - - -] Post-network exception: icontrol_driver: 'NoneType' object has no attribute '__getitem__'
2017-05-05 17:52:21.301 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-6eb29ee0-c7a0-409f-839b-f2314b803014 3c16178c83cd4a378b68c4bf50f7807a 62941e875f374220a5f712a01ff271fe - - -] 'NoneType' object has no attribute '__getitem__'
2017-05-05 17:52:21.301 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Traceback (most recent call last):
2017-05-05 17:52:21.301 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 1266, in _common_service_handler
2017-05-05 17:52:21.301 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     raise error
2017-05-05 17:52:21.301 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver TypeError: 'NoneType' object has no attribute '__getitem__'
2017-05-05 17:52:21.301 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver

Additional exception logging reports:

2017-05-05 17:52:21.296 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-6eb29ee0-c7a0-409f-839b-f2314b803014 3c16178c83cd4a378b68c4bf50f7807a 62941e875f374220a5f712a01ff271fe - - -] JD - This exception!!
2017-05-05 17:52:21.296 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Traceback (most recent call last):
2017-05-05 17:52:21.296 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 1257, in _common_service_handler
2017-05-05 17:52:21.296 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     service, all_subnet_hints)
2017-05-05 17:52:21.296 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py", line 619, in post_service_networking
2017-05-05 17:52:21.296 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     self.update_bigip_l2(service)
2017-05-05 17:52:21.296 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py", line 666, in update_bigip_l2
2017-05-05 17:52:21.296 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     self.delete_bigip_member_l2(bigip, loadbalancer, member)
2017-05-05 17:52:21.296 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py", line 721, in delete_bigip_member_l2
2017-05-05 17:52:21.296 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     'mac_address': member['port']['mac_address']}
2017-05-05 17:52:21.296 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver TypeError: 'NoneType' object has no attribute '__getitem__'
2017-05-05 17:52:21.296 30840 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver

Creating a dummy port in the subnet with the IP of the member avoids the issue seen above. 

#### Deployment
openstack-ansible with 3 infra nodes (3 neutron server and 3 neutron agent containers)

**Comment by dflanigan** [comment]
@szakeri and @pjbreaux do we already have an github issue for this issue ?

**Comment by pjbreaux** [comment]
We don't, as far as I know. This is very likely the issue @szakeri and I are troubleshooting currently.

**Comment by mattgreene** [comment]
This issue becomes obsolete with https://github.com/F5Networks/f5-openstack-lbaasv2-driver/pull/586.
