### ISSUE TITLE
Won't be able to add pool member in pair of F5 VE

### ISSUE THREAD

**Issue by panxia6679** [F5Networks/f5-openstack-agent#775]
Won't be able to add pool member in pair of F5 VE.

### F5 VE version
11.6.1

#### Agent Version
f5-openstack-agent (9.3.0b2)

#### Operating System
ubuntu trusty

#### OpenStack Release
mitaka

#### Description
When adding member to pool, it prompts with the following error in f5-oslbaasv2-agent.log
neutron lbaas-member-create --subnet  lbaas_backend --address 192.168.50.4  --protocol-port 80 test-lb-pool-http

Please note, the environment works on singlealone type before verifying pair.

~~~
root@controller1:~# nova list
+--------------------------------------+----------+--------+------------+-------------+-----------------------------+
| ID                                   | Name     | Status | Task State | Power State | Networks                    |
+--------------------------------------+----------+--------+------------+-------------+-----------------------------+
| 69c3febf-12d2-4fb3-abee-36ae4b722dd1 | backend1 | ACTIVE | -          | Running     | lbaas_backend=192.168.50.4  |
~~~

~~~
2017-06-22 08:23:33.631 13227 DEBUG root [req-a13ba34f-c64c-41d0-8d50-110b5525ec15 3f430e1684204142a8b8eb494693d9e4 78e784d0b6314b3aba5e361c41176295 - - -] RESPONSE::STATUS: 200 Content-Type: application/json Content-Encoding: None
Text: u'{"kind":"tm:ltm:pool:members:membersstate","name":"192.168.50.4%1:80","partition":"Project_78e784d0b6314b3aba5e361c41176295","fullPath":"/Project_78e784d0b6314b3aba5e361c41176295/192.168.50.4%1:80","generation":41,"selfLink":"https://localhost/mgmt/tm/ltm/pool/~Project_78e784d0b6314b3aba5e361c41176295~Project_9140d76a-a791-42a0-bbd8-e1989a2443a2/members/~Project_78e784d0b6314b3aba5e361c41176295~192.168.50.4%251:80?ver=11.6.1","address":"192.168.50.4%1","connectionLimit":0,"dynamicRatio":1,"ephemeral":"false","fqdn":{"autopopulate":"disabled"},"inheritProfile":"enabled","logging":"disabled","monitor":"default","priorityGroup":0,"rateLimit":"disabled","ratio":1,"session":"user-enabled","state":"unchecked"}' wrapper /opt/bbc/openstack-2016.1-bbc248/neutron/local/lib/python2.7/site-packages/icontrol/session.py:265
2017-06-22 08:23:33.632 13227 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-a13ba34f-c64c-41d0-8d50-110b5525ec15 3f430e1684204142a8b8eb494693d9e4 78e784d0b6314b3aba5e361c41176295 - - -] 'address'
2017-06-22 08:23:33.632 13227 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Traceback (most recent call last):
2017-06-22 08:23:33.632 13227 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/opt/bbc/openstack-2016.1-bbc248/neutron/local/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 1237, in _common_service_handler
2017-06-22 08:23:33.632 13227 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     all_subnet_hints)
2017-06-22 08:23:33.632 13227 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/opt/bbc/openstack-2016.1-bbc248/neutron/local/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/lbaas_builder.py", line 70, in assure_service
2017-06-22 08:23:33.632 13227 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     self._assure_members(service, all_subnet_hints)
2017-06-22 08:23:33.632 13227 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/opt/bbc/openstack-2016.1-bbc248/neutron/local/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/lbaas_builder.py", line 261, in _assure_members
2017-06-22 08:23:33.632 13227 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     self.pool_builder.update_member(svc, bigips)
2017-06-22 08:23:33.632 13227 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/opt/bbc/openstack-2016.1-bbc248/neutron/local/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/pool_service.py", line 185, in update_member
2017-06-22 08:23:33.632 13227 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     member.pop("address")
2017-06-22 08:23:33.632 13227 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver KeyError: 'address'
2017-06-22 08:23:33.632 13227 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver
2017-06-22 08:23:33.632 13227 DEBUG f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-a13ba34f-c64c-41d0-8d50-110b5525ec15 3f430e1684204142a8b8eb494693d9e4 78e784d0b6314b3aba5e361c41176295 - - -] _update_service_status update_service_status /opt/bbc/openstack-2016.1-bbc248/neutron/local/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py:1282
~~~

#### Deployment
two controllers with a f5 agent on each one.

root@controller2:~# cat /etc/neutron/services/f5/f5-openstack-agent.ini
[DEFAULT]
debug = True
periodic_interval = 10
f5_ha_type = pair
f5_external_physical_mappings = default:1.2:True
f5_vtep_folder = Common
f5_vtep_selfip_name = selfip.lb-data
advertised_tunnel_types = vxlan
f5_populate_static_arp = False 
l2_population = True
f5_global_routed_mode = False
use_namespaces = True
max_namespaces_per_tenant = 1
f5_route_domain_strictness = False
f5_snat_mode = True
f5_snat_addresses_per_subnet = 1
f5_common_external_networks = False
f5_bigip_lbaas_device_driver = f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver.iControlDriver
icontrol_hostname = <ip>,<ip>
icontrol_username = admin
icontrol_password = admin

**Comment by panxia6679** [comment]
the problem won't exist when picking up the latest branch of mitaka from 9.3.0b2.
